# Generated by Django 5.1.5 on 2025-02-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Faculty',
            new_name='faculty',
        ),
    ]
