# Generated by Django 5.1.5 on 2025-02-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_faculty_group_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teacher'),
        ),
    ]
