# Generated by Django 5.1.5 on 2025-03-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_group_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'teacher__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.person'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_disciplines', to='education.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='education.department'),
        ),
    ]
